## Intelligent Systems - HW5
### Soroush Mesforush Mashhad
#### SID: 810198472

In [1]:
import numpy as np
import pandas as pd
import seaborn as sn
from matplotlib import pyplot as plt
import random
from statistics import mean,stdev

In [2]:
DATA_WIDTH=28
DATA_HEIGHT=28
NUMBER_OF_TRAINING_EXAMPLES=5000
NUMBER_OF_VALIDATION_EXAMPLES=1000

ALL_TRAINING_IMAGES=[]
ALL_TRAINING_LABELS=[]
ALL_VALIDATION_IMAGES=[]
ALL_VALIDATION_LABELS=[]

'''
Convert ASC-II pixel into numerical data and vice versa
    - ' ' is converted to ..., which means it's part of the background
    - '#' is converted to ..., part of the image interior
    - '+' is converted to ..., part of the edges
    
'''

def _pixel_to_value(character):
    if(character == ' '):
        return 0
    elif(character == '#'):
        return 1
    elif(character == '+'):
        return 2
def _value_to_pixel(value):
    if(value == 0):
        return ' '
    elif(value == 1):
        return '#'
    elif(value == 2):
        return '+'
'''
Function for loading data and label files
'''

def _load_data_file(filename, n, width, height):
    fin = [l[:-1] for l in open(filename).readlines()]
    fin.reverse()
    items = []
    for i in range(n):
        data = []
        for j in range(height):
            row = map(_pixel_to_value, list(fin.pop()))
            data.append(list(row))
        items.append(data)
    return items
        
def _load_label_file(filename, n):
    fin = [l[:-1] for l in open(filename).readlines()]
    labels = []
    for i in range(n):
        labels.append(int(fin[i]))
    return labels

def _load_all_data():
    global ALL_TRAINING_IMAGES
    global ALL_TRAINING_LABELS
    global ALL_VALIDATION_IMAGES
    global ALL_VALIDATION_LABELS

    ALL_TRAINING_IMAGES = _load_data_file("trainingimages",
        NUMBER_OF_TRAINING_EXAMPLES, DATA_WIDTH, DATA_HEIGHT)
    ALL_TRAINING_LABELS = _load_label_file("traininglabels",
        NUMBER_OF_TRAINING_EXAMPLES)

    ALL_VALIDATION_IMAGES = _load_data_file("validationimages",
        NUMBER_OF_VALIDATION_EXAMPLES, DATA_WIDTH, DATA_HEIGHT)
    ALL_VALIDATION_LABELS = _load_label_file("validationlabels",
        NUMBER_OF_VALIDATION_EXAMPLES)

'''
Function for printing digits
'''

def _print_digit_image(data):
    for row in range(len(data)):
        print(''.join(map(_value_to_pixel, data[row])))
    
_load_all_data()

example_number = random.randint(0, NUMBER_OF_TRAINING_EXAMPLES)
print("Printing digit example #" + str(example_number + 1) + " with label: " \
        + str(ALL_TRAINING_LABELS[example_number]))
_print_digit_image(ALL_TRAINING_IMAGES[example_number])


Printing digit example #3292 with label: 3
                            
                            
                            
                            
              +###+         
           ++#### #+        
           +###++##+        
            +++  +#+        
                 +#+        
                 #+         
               ++#+         
               +##+         
            ++###+          
            #####+          
            +####++         
            +++ ##+         
               +##+         
                ##+         
               +##+         
       +     + ##+          
      +#    ++###           
      +##++#####+           
      +#######++            
       +####++              
                            
                            
                            
                            


In [3]:
'''
Extract 'basic' features, i.e., whether a pixel is in the background or part of the digit
'''

'''
Extract advanced features that you will come up with. For example: 
**Note that it's not mandatory to use the features listed above.
'''

    # Calculate the width and height of the digit
    # Calculate the number of #s and +s in the top half ( or in any other part)
    # Define a rowlimit and investigate if the amount of #s/+s surpasses the limit
    


"\nExtract advanced features that you will come up with. For example: \n**Note that it's not mandatory to use the features listed above.\n"

### Preliminary Testing

In [4]:
_load_all_data()

In [5]:
_load_all_data()
test = ''.join(map(_value_to_pixel, ALL_TRAINING_IMAGES[7][5]))
print(test[19])

#


We shall perform the Naive bayes algorithm with functions for brevity.

In [6]:
def TrainTestData(ALL_TRAINING_IMAGES,ALL_VALIDATION_IMAGES):
    return np.array(ALL_TRAINING_IMAGES),np.array(ALL_VALIDATION_IMAGES)

In [7]:
def TrainTestLabels(ALL_TRAINING_LABELS,ALL_VALIDATION_LABELS):
    return np.array(ALL_TRAINING_LABELS),np.array(ALL_VALIDATION_LABELS)

I shall extract 3 of the features suggested in the project, the height, the width and the count of # and the count of +

First we shall go for the height, each number has 28 lines, but the height is different for each scenario, take a look at the following:

In [8]:
print("Printing digit example #" + str(250) + " with label: " \
        + str(ALL_TRAINING_LABELS[250]))
_print_digit_image(ALL_TRAINING_IMAGES[250])


Printing digit example #250 with label: 3
                            
                            
                            
                            
                            
                            
                            
                            
    +++++++++               
   +##########+ ++          
   ##+++++  ######+         
   ++       ++++####        
                +###        
           ++ ++## #+       
          +########+        
          +#########+       
           +  +  +###+      
                  + # +     
          ++        +##     
          ##++++++++###     
           ####### ###+     
           ++##++###++      
                            
                            
                            
                            
                            
                            


In [9]:
xtrain,xval = TrainTestData(ALL_TRAINING_IMAGES,ALL_VALIDATION_IMAGES)
ytrain,yval = TrainTestLabels(ALL_TRAINING_LABELS,ALL_VALIDATION_LABELS)

The following function shall give us an idea to calculate the height of each number

In [10]:
Th

In [11]:
NumberShower(xtrain[250])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 2 1 1 1 1 1 1 1 1 1 1 2 0 2 2 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 1 2 2 2 2 2 0 0 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0]
[0 0 0 2 2 0 0 0 0 0 0 0 2 2 2 2 1 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 2 2 0 2 2 1 1 0 1 2 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 2 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 2 1 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 2 0 0 2 0 0 2 1 1 1 2 0 0 0 0 0 0]
[0 0 0 0 0 0 0

As we can see an outline of the number 3 can be seen via 1 and 2 numbers, so to calculate the height, it is the obvious that each row that the sum of it is not zero shoulb be considered in the height, so we design the following function

In [12]:
def HeightCalc(Image):
    height = 0
    for i in range(DATA_HEIGHT):
        if(sum(Image[i])!=0):
            height+=1
    return height

In [13]:
HeightCalc(xtrain[250])

14

No we shall implement the width function, once again we shall draw the above number to come up with an algorithm

In [14]:
NumberShower(xtrain[250])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 2 1 1 1 1 1 1 1 1 1 1 2 0 2 2 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 1 2 2 2 2 2 0 0 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0]
[0 0 0 2 2 0 0 0 0 0 0 0 2 2 2 2 1 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 2 2 0 2 2 1 1 0 1 2 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 2 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 2 1 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 2 0 0 2 0 0 2 1 1 1 2 0 0 0 0 0 0]
[0 0 0 0 0 0 0

It is obvious that the width algorithm is same as the height but for columns so we have the following function

In [15]:
def WidthCalc(Image):
    width = 0
    for i in range(DATA_WIDTH):
        if(sum(Image[:,i])!=0):
            width+=1
    return width

In [16]:
x = WidthCalc(xtrain[250])
x

20

Now we shall count the number of # in each image, to do so we must count the number of 1s in the matrix

In [17]:
def HashtagCounter(Image):
    HashtagNum = 0
    for i in range(DATA_WIDTH):
        HashtagNum+=np.count_nonzero((Image[:,i]==1))
    return HashtagNum

In [18]:
x = HashtagCounter(xtrain[250])
x

71

After finding 3 features, we must go on to implement the naive bayes algorithm, we need a function to categorize the training data and validation data in the correct classes with the corresponding labels 0 to 9

In [19]:
def CategorizerByIndice(TrainLabels,ValLabels):
    TrainCategory = []
    ValCategory = []
    for i in range(0,10):
        valtemp=[]
        for k in range(1000):
            if ValLabels[k]==i:
                valtemp.append(k)
        ValCategory.append(valtemp)
    for l in range(0,10):
        traintemp=[]
        for j in range(5000):
            if TrainLabels[j]==l:
                traintemp.append(j)
        TrainCategory.append(traintemp)
    return TrainCategory,ValCategory

In [20]:
def CategorizerByClass(Label,Category):
    for m in range(10):
        if Label in Category[m]:
            return m
        else:
            continue

In [21]:
TrainCategory,ValCategory= CategorizerByIndice(ytrain,yval)

Now we write a function to calculate the prior probability.

In [22]:
def PriorProbCalc(TrainCategory):
    Prior = []
    for i in range(0,10):
        prob = len(TrainCategory[i])/NUMBER_OF_TRAINING_EXAMPLES
        Prior.append(prob)
    return Prior

In [23]:
PriorProbs = PriorProbCalc(TrainCategory)
PriorProbs

[0.0958, 0.1126, 0.0976, 0.0986, 0.107, 0.0868, 0.1002, 0.11, 0.0924, 0.099]

Now we shall go on to implement the Naive Bayes algorithm, to do so we fit the probabiliy of each feature using a gaussian distribution as implied in class,Before doing so we need to save the features for each class accordingly.

In [24]:
def FeatureSaver(xtrain):
    AllFeatures  = []
    temp = []
    for i in range(3):
        AllFeatures.append(list(temp))
    for j in range(10):
        AllFeatures[0].append(list(temp))
        AllFeatures[1].append(list(temp))  
        AllFeatures[2].append(list(temp))       
    for k in range(5000):
        Category = CategorizerByClass(k,TrainCategory)
        AllFeatures[0][Category].append(HeightCalc(xtrain[k]))
        AllFeatures[1][Category].append(WidthCalc(xtrain[k]))
        AllFeatures[2][Category].append(HashtagCounter(xtrain[k]))
    return AllFeatures

In [25]:
AllFeatures = FeatureSaver(xtrain)

Now we go on to the Gaussian model we opt to use

In [26]:
def Gaussian(xtrain,AllFeatures):
    AllFeaturesGaussian  = []
    temp = []
    for i in range(3):
        AllFeaturesGaussian.append(list(temp))
    for j in range(10):
        AllFeaturesGaussian[0].append(list(temp))
        AllFeaturesGaussian[1].append(list(temp))  
        AllFeaturesGaussian[2].append(list(temp))       
    for k in range(10):
        AllFeaturesGaussian[0][k].append(np.mean(AllFeatures[0][k]))
        AllFeaturesGaussian[0][k].append(np.var(AllFeatures[0][k]))
        AllFeaturesGaussian[1][k].append(np.mean(AllFeatures[1][k]))
        AllFeaturesGaussian[1][k].append(np.var(AllFeatures[1][k]))
        AllFeaturesGaussian[2][k].append(np.mean(AllFeatures[2][k]))
        AllFeaturesGaussian[2][k].append(np.var(AllFeatures[2][k]))
    return AllFeaturesGaussian

In [27]:
AllFeaturesGaussian=Gaussian(xtrain,AllFeatures)

In the next step we calculate P(X|Y=c) via a gaussian function and then we are just about done

In [28]:
def NaiveBayesFinalAndAccuracy(AllFeatures,xval,yval,xtrain):
    AllFeaturesGaussian=Gaussian(xtrain,AllFeatures)
    Pred = []
    true = 0
    for k in range(1000):
        ProbArr=[]
        for i in range(0,10):
            Prob1 = (1/(np.sqrt(AllFeaturesGaussian[0][i][1]*np.pi*2)))*np.exp((-.5*((HeightCalc(xval[k])-AllFeaturesGaussian[0][i][0])**2)/(AllFeaturesGaussian[0][i][1])))
            Prob2 = (1/(np.sqrt(AllFeaturesGaussian[1][i][1]*np.pi*2)))*np.exp((-.5*((WidthCalc(xval[k])-AllFeaturesGaussian[1][i][0])**2)/(AllFeaturesGaussian[1][i][1])))
            Prob3 = (1/(np.sqrt(AllFeaturesGaussian[2][i][1]*np.pi*2)))*np.exp((-.5*((HashtagCounter(xval[k])-AllFeaturesGaussian[2][i][0])**2)/(AllFeaturesGaussian[2][i][1])))
            ProbArr.append(Prob1*Prob2*Prob3*PriorProbs[i])
        Pred.append(np.argmax(ProbArr))
    for i in range(len(Pred)):
        if yval[i]==Pred[i]:
            true+=1
    Acc= true/NUMBER_OF_VALIDATION_EXAMPLES * 100
    print(f'Accuracy of Naive Bayes is {Acc}%')

In [29]:
NaiveBayesFinalAndAccuracy(AllFeatures,xval,yval,xtrain)

Accuracy of Naive Bayes is 22.7%
